language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t xinyi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xinyi/docker-react

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "test"
  env: "Test-env"
  bucket_name: "elasticbeanstalk-us-west-1-003738152073"
  bucket_path: "test"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key:
    secure: $secret_access_key
